name: Release
on:
  push:
    branches:
      - semantic-release
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build package
        run: yarn build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: cd build && npx semantic-release



# permissions:
#   contents: read
#   pages: write
#   id-token: write
#   packages: write

# name: Build and Publish NPM package
# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#       - name: Prepare repository
#         run: git fetch --unshallow --tags
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 16.13.2
#           registry-url: "https://npm.pkg.github.com"
#           scope: "@jhahn678"
#           always-auth: true
#       - name: Create and Publish Release NPM
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           yarn install --frozen-lockfile
#           yarn build:release